# Generated by Django 3.0.6 on 2020-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDjango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter', models.TextField(blank=True, db_column='ADAPTER', null=True)),
                ('data_load', models.TextField(blank=True, db_column='DATA_LOAD', null=True)),
                ('sender', models.TextField(blank=True, db_column='SENDER', null=True)),
                ('receiver', models.TextField(blank=True, db_column='RECEIVER', null=True)),
                ('interface_name', models.TextField(blank=True, db_column='INTERFACE_NAME', null=True)),
                ('type_error', models.TextField(blank=True, db_column='TYPE_ERROR', null=True)),
                ('msg_id', models.TextField(blank=True, db_column='MSG_ID', null=True)),
                ('error_text', models.TextField(blank=True, db_column='ERROR_TEXT', null=True)),
                ('update_status', models.TextField(db_column='UPDATE_STATUS')),
                ('update_user', models.TextField(db_column='UPDATE_USER')),
            ],
            options={
                'db_table': 'TEST_DJANGO',
                'managed': False,
            },
        ),
    ]
